2023-10-06 00:56:50,119 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Fri, 06 Oct 2023 00:56:50 +0000. Up 8.72 seconds.
2023-10-06 00:56:50,119 - main.py[DEBUG]: No kernel command line url found.
2023-10-06 00:56:50,119 - main.py[DEBUG]: Closing stdin.
2023-10-06 00:56:50,121 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2023-10-06 00:56:50,135 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-10-06 00:56:50,142 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2023-10-06 00:56:50,143 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2023-10-06 00:56:50,148 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2023-10-06 00:56:50,148 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2023-10-06 00:56:50,154 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2023-10-06 00:56:50,166 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2023-10-06 00:56:50,185 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2023-10-06 00:56:50,186 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2023-10-06 00:56:50,206 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2023-10-06 00:56:50,207 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-10-06 00:56:50,234 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2023-10-06 00:56:50,235 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-10-06 00:56:50,262 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2023-10-06 00:56:50,263 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-10-06 00:56:50,281 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2023-10-06 00:56:50,282 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-10-06 00:56:50,327 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2023-10-06 00:56:50,328 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2023-10-06 00:56:50,329 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2023-10-06 00:56:50,330 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2023-10-06 00:56:50,330 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2023-10-06 00:56:50,333 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2023-10-06 00:56:50,337 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2023-10-06 00:56:50,338 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2023-10-06 00:56:50,339 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2023-10-06 00:56:50,340 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2023-10-06 00:56:50,341 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2023-10-06 00:56:50,342 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:50,366 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:50,376 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2023-10-06 00:56:50,386 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2023-10-06 00:56:50,387 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2023-10-06 00:56:50,387 - stages.py[DEBUG]: no cache found
2023-10-06 00:56:50,387 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2023-10-06 00:56:50,387 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-10-06 00:56:50,395 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-10-06 00:56:50,395 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2023-10-06 00:56:50,402 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2023-10-06 00:56:50,403 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2023-10-06 00:56:50,403 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2023-10-06 00:56:50,404 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2023-10-06 00:56:50,404 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2023-10-06 00:56:50,404 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2023-10-06 00:56:50,404 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2023-10-06 00:56:50,404 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2023-10-06 00:56:50,404 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2023-10-06 00:56:50,404 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2023-10-06 00:56:50,405 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2023-10-06 00:56:50,405 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.001 seconds
2023-10-06 00:56:50,405 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2023-10-06 00:56:50,406 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2023-10-06 00:56:50,406 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2023-10-06 00:56:50,412 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2023-10-06 00:56:50,457 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2023-10-06 00:56:50,457 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2023-10-06 00:56:50,457 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,461 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2023-10-06 00:56:50,461 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2023-10-06 00:56:50,461 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,477 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2441b) after 1 attempts
2023-10-06 00:56:50,479 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,486 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2023-10-06 00:56:50,487 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,497 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2023-10-06 00:56:50,497 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,502 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2023-10-06 00:56:50,502 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,507 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2023-10-06 00:56:50,507 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,511 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2023-10-06 00:56:50,511 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,526 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2023-10-06 00:56:50,526 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,531 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2023-10-06 00:56:50,531 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,536 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2023-10-06 00:56:50,536 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,539 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2023-10-06 00:56:50,539 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,546 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2023-10-06 00:56:50,546 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,549 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2023-10-06 00:56:50,549 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,556 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2023-10-06 00:56:50,556 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,558 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2023-10-06 00:56:50,559 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,566 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2023-10-06 00:56:50,566 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,576 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2023-10-06 00:56:50,576 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,586 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2023-10-06 00:56:50,586 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,599 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2023-10-06 00:56:50,599 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,602 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2023-10-06 00:56:50,603 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,616 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/ (200, 230b) after 1 attempts
2023-10-06 00:56:50,616 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,619 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/ipv4-associations/ (200, 13b) after 1 attempts
2023-10-06 00:56:50,619 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/ipv4-associations/54.71.248.131' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/ipv4-associations/54.71.248.131', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,626 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/ipv4-associations/54.71.248.131 (200, 13b) after 1 attempts
2023-10-06 00:56:50,626 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,636 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/device-number (200, 1b) after 1 attempts
2023-10-06 00:56:50,636 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,647 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/interface-id (200, 21b) after 1 attempts
2023-10-06 00:56:50,648 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,656 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/local-hostname (200, 43b) after 1 attempts
2023-10-06 00:56:50,656 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,659 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/local-ipv4s (200, 13b) after 1 attempts
2023-10-06 00:56:50,660 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,668 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/mac (200, 17b) after 1 attempts
2023-10-06 00:56:50,669 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,672 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/owner-id (200, 12b) after 1 attempts
2023-10-06 00:56:50,672 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,686 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/public-hostname (200, 49b) after 1 attempts
2023-10-06 00:56:50,686 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,697 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/public-ipv4s (200, 13b) after 1 attempts
2023-10-06 00:56:50,697 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,706 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/security-group-ids (200, 20b) after 1 attempts
2023-10-06 00:56:50,706 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,717 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/security-groups (200, 56b) after 1 attempts
2023-10-06 00:56:50,718 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,720 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/subnet-id (200, 24b) after 1 attempts
2023-10-06 00:56:50,721 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,726 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2023-10-06 00:56:50,726 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,729 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-id (200, 21b) after 1 attempts
2023-10-06 00:56:50,729 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,736 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2023-10-06 00:56:50,736 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,739 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:a9:75:34:0c:c9/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2023-10-06 00:56:50,739 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,747 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2023-10-06 00:56:50,747 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,756 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2023-10-06 00:56:50,756 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,766 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2023-10-06 00:56:50,766 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,776 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2023-10-06 00:56:50,776 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,780 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2023-10-06 00:56:50,780 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,786 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2023-10-06 00:56:50,786 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,788 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2023-10-06 00:56:50,789 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,796 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2023-10-06 00:56:50,796 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,798 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2023-10-06 00:56:50,799 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,806 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2023-10-06 00:56:50,806 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,826 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 43b) after 1 attempts
2023-10-06 00:56:50,826 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,836 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2023-10-06 00:56:50,836 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,839 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2023-10-06 00:56:50,839 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,856 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2023-10-06 00:56:50,856 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,859 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2023-10-06 00:56:50,859 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,866 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 43b) after 1 attempts
2023-10-06 00:56:50,866 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,869 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 13b) after 1 attempts
2023-10-06 00:56:50,869 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,871 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2023-10-06 00:56:50,872 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,876 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2023-10-06 00:56:50,876 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,878 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 49b) after 1 attempts
2023-10-06 00:56:50,878 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,887 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2023-10-06 00:56:50,887 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,890 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2023-10-06 00:56:50,890 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,896 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2023-10-06 00:56:50,896 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,906 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2023-10-06 00:56:50,906 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,918 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 477b) after 1 attempts
2023-10-06 00:56:50,918 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,921 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1167b) after 1 attempts
2023-10-06 00:56:50,922 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,936 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1487b) after 1 attempts
2023-10-06 00:56:50,936 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-10-06 00:56:50,939 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2023-10-06 00:56:50,939 - util.py[DEBUG]: Crawl of metadata service took 0.535 seconds
2023-10-06 00:56:50,943 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2023-10-06 00:56:50,944 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2023-10-06 00:56:50,945 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2023-10-06 00:56:50,945 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2023-10-06 00:56:50,946 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmplm7trggq) - w: [600] 11970 bytes/chars
2023-10-06 00:56:50,948 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpz0c0pfsq) - w: [644] 7876 bytes/chars
2023-10-06 00:56:50,948 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2023-10-06 00:56:50,948 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2023-10-06 00:56:50,948 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-10-06 00:56:50,948 - util.py[DEBUG]: Read 2514 bytes from /etc/cloud/cloud.cfg
2023-10-06 00:56:50,948 - util.py[DEBUG]: Attempting to load yaml from string of length 2514 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:50,965 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2023-10-06 00:56:50,966 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2023-10-06 00:56:50,966 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:50,967 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2023-10-06 00:56:50,967 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2023-10-06 00:56:50,967 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:50,986 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-10-06 00:56:50,986 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-10-06 00:56:50,986 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:50,993 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2023-10-06 00:56:50,993 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2023-10-06 00:56:50,993 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,006 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-10-06 00:56:51,006 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,006 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-10-06 00:56:51,007 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-10-06 00:56:51,007 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-02f5f4c1d71eb856a'
2023-10-06 00:56:51,008 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a (recursive=True)
2023-10-06 00:56:51,014 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/handlers (recursive=False)
2023-10-06 00:56:51,015 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a (recursive=True)
2023-10-06 00:56:51,022 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/scripts (recursive=False)
2023-10-06 00:56:51,023 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a (recursive=True)
2023-10-06 00:56:51,032 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem (recursive=False)
2023-10-06 00:56:51,032 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-02f5f4c1d71eb856a/datasource (quiet=False)
2023-10-06 00:56:51,032 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/datasource - wb: [644] 29 bytes
2023-10-06 00:56:51,033 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/datasource (recursive=False)
2023-10-06 00:56:51,034 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/datasource (recursive=False)
2023-10-06 00:56:51,045 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2023-10-06 00:56:51,046 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2023-10-06 00:56:51,047 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2023-10-06 00:56:51,048 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2023-10-06 00:56:51,048 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2023-10-06 00:56:51,048 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2023-10-06 00:56:51,049 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2023-10-06 00:56:51,050 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2023-10-06 00:56:51,050 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2023-10-06 00:56:51,051 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2023-10-06 00:56:51,051 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2023-10-06 00:56:51,052 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2023-10-06 00:56:51,052 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2023-10-06 00:56:51,053 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2023-10-06 00:56:51,054 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12538 bytes
2023-10-06 00:56:51,055 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/obj.pkl (recursive=False)
2023-10-06 00:56:51,058 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/obj.pkl (recursive=False)
2023-10-06 00:56:51,059 - main.py[DEBUG]: [net] init will now be targeting instance id: i-02f5f4c1d71eb856a. new=True
2023-10-06 00:56:51,059 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-10-06 00:56:51,059 - util.py[DEBUG]: Read 2514 bytes from /etc/cloud/cloud.cfg
2023-10-06 00:56:51,059 - util.py[DEBUG]: Attempting to load yaml from string of length 2514 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,073 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2023-10-06 00:56:51,073 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2023-10-06 00:56:51,073 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,086 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2023-10-06 00:56:51,086 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2023-10-06 00:56:51,086 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,089 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-10-06 00:56:51,089 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-10-06 00:56:51,089 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,106 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2023-10-06 00:56:51,107 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2023-10-06 00:56:51,107 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,109 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-10-06 00:56:51,110 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,110 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-10-06 00:56:51,111 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-10-06 00:56:51,111 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-10-06 00:56:51,111 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2023-10-06 00:56:51,111 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2023-10-06 00:56:51,112 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2023-10-06 00:56:51,112 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2023-10-06 00:56:51,112 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2023-10-06 00:56:51,112 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2023-10-06 00:56:51,112 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2023-10-06 00:56:51,112 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2023-10-06 00:56:51,112 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2023-10-06 00:56:51,112 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2023-10-06 00:56:51,112 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2023-10-06 00:56:51,113 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2023-10-06 00:56:51,113 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-10-06 00:56:51,113 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-10-06 00:56:51,113 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2023-10-06 00:56:51,113 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2023-10-06 00:56:51,113 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2023-10-06 00:56:51,113 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2023-10-06 00:56:51,113 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2023-10-06 00:56:51,113 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2023-10-06 00:56:51,113 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2023-10-06 00:56:51,114 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2023-10-06 00:56:51,114 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2023-10-06 00:56:51,114 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2023-10-06 00:56:51,114 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2023-10-06 00:56:51,114 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2023-10-06 00:56:51,114 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2023-10-06 00:56:51,114 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2023-10-06 00:56:51,114 - stages.py[DEBUG]: network config disabled by system_cfg
2023-10-06 00:56:51,114 - stages.py[INFO]: network config is disabled by system_cfg
2023-10-06 00:56:51,114 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2023-10-06 00:56:51,114 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2023-10-06 00:56:51,114 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/user-data.txt - wb: [600] 2441 bytes
2023-10-06 00:56:51,125 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/user-data.txt (recursive=False)
2023-10-06 00:56:51,127 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/user-data.txt (recursive=False)
2023-10-06 00:56:51,129 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,133 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/user-data.txt.i - wb: [600] 2463 bytes
2023-10-06 00:56:51,133 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/user-data.txt.i (recursive=False)
2023-10-06 00:56:51,135 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/user-data.txt.i (recursive=False)
2023-10-06 00:56:51,135 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data.txt - wb: [600] 0 bytes
2023-10-06 00:56:51,136 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data.txt (recursive=False)
2023-10-06 00:56:51,137 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data.txt (recursive=False)
2023-10-06 00:56:51,140 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data.txt.i - wb: [600] 308 bytes
2023-10-06 00:56:51,141 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data.txt.i (recursive=False)
2023-10-06 00:56:51,142 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data.txt.i (recursive=False)
2023-10-06 00:56:51,142 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data2.txt - wb: [600] 0 bytes
2023-10-06 00:56:51,143 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data2.txt (recursive=False)
2023-10-06 00:56:51,144 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data2.txt (recursive=False)
2023-10-06 00:56:51,156 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data2.txt.i - wb: [600] 308 bytes
2023-10-06 00:56:51,157 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data2.txt.i (recursive=False)
2023-10-06 00:56:51,159 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/vendor-data2.txt.i (recursive=False)
2023-10-06 00:56:51,160 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-10-06 00:56:51,161 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-37-217.us-west-2.compute.internal (ip-172-31-37-217)
2023-10-06 00:56:51,161 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-37-217.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:51,363 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-37-217.us-west-2.compute.internal
2023-10-06 00:56:51,363 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-37-217.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:51,371 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmp3q14_w77) - w: [644] 92 bytes/chars
2023-10-06 00:56:51,372 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/consume_data - wb: [644] 25 bytes
2023-10-06 00:56:51,373 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/consume_data (recursive=False)
2023-10-06 00:56:51,385 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/consume_data (recursive=False)
2023-10-06 00:56:51,391 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/consume_data'>)
2023-10-06 00:56:51,391 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2023-10-06 00:56:51,392 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2023-10-06 00:56:51,397 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2023-10-06 00:56:51,397 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2023-10-06 00:56:51,397 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2023-10-06 00:56:51,397 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2023-10-06 00:56:51,397 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2023-10-06 00:56:51,397 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2023-10-06 00:56:51,397 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2023-10-06 00:56:51,406 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2023-10-06 00:56:51,406 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,406 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,406 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,406 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,406 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,406 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2023-10-06 00:56:51,407 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2023-10-06 00:56:51,407 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2023-10-06 00:56:51,407 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,409 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2023-10-06 00:56:51,409 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2023-10-06 00:56:51,410 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2023-10-06 00:56:51,410 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1792 bytes
2023-10-06 00:56:51,411 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/scripts/user-data.txt (recursive=False)
2023-10-06 00:56:51,412 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/scripts/user-data.txt (recursive=False)
2023-10-06 00:56:51,413 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2023-10-06 00:56:51,414 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/cloud-config.txt - wb: [600] 154 bytes
2023-10-06 00:56:51,415 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/cloud-config.txt (recursive=False)
2023-10-06 00:56:51,416 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/cloud-config.txt (recursive=False)
2023-10-06 00:56:51,417 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,417 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,417 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,417 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,417 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2023-10-06 00:56:51,417 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2023-10-06 00:56:51,417 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2023-10-06 00:56:51,418 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2023-10-06 00:56:51,418 - stages.py[DEBUG]: no vendordata from datasource
2023-10-06 00:56:51,418 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2023-10-06 00:56:51,418 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2023-10-06 00:56:51,418 - stages.py[DEBUG]: no vendordata2 from datasource
2023-10-06 00:56:51,418 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2023-10-06 00:56:51,418 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-10-06 00:56:51,418 - util.py[DEBUG]: Read 2514 bytes from /etc/cloud/cloud.cfg
2023-10-06 00:56:51,418 - util.py[DEBUG]: Attempting to load yaml from string of length 2514 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,449 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2023-10-06 00:56:51,449 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2023-10-06 00:56:51,449 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,451 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2023-10-06 00:56:51,451 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2023-10-06 00:56:51,451 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,454 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-10-06 00:56:51,454 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-10-06 00:56:51,454 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,460 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2023-10-06 00:56:51,461 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2023-10-06 00:56:51,461 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,465 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-10-06 00:56:51,466 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,466 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-10-06 00:56:51,466 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2023-10-06 00:56:51,466 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2023-10-06 00:56:51,466 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,468 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,468 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,610 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2023-10-06 00:56:51,610 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2023-10-06 00:56:51,610 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2023-10-06 00:56:51,616 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2023-10-06 00:56:51,617 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16678 bytes
2023-10-06 00:56:51,627 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/obj.pkl (recursive=False)
2023-10-06 00:56:51,629 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/obj.pkl (recursive=False)
2023-10-06 00:56:51,629 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2023-10-06 00:56:51,630 - main.py[DEBUG]: no di_report found in config.
2023-10-06 00:56:51,631 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,632 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,645 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,646 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,649 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,649 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,652 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,656 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,665 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,665 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,668 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,669 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,673 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,673 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,686 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,686 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,690 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,690 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,705 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,705 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,708 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,708 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,715 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,715 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,718 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,718 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,722 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,722 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,736 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,736 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,741 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:51,741 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:51,745 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-10-06 00:56:51,746 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2023-10-06 00:56:51,746 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2023-10-06 00:56:51,746 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fe15f32adc0>)
2023-10-06 00:56:51,746 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2023-10-06 00:56:51,747 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2023-10-06 00:56:51,747 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2023-10-06 00:56:51,747 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2023-10-06 00:56:51,747 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_seed_random - wb: [644] 25 bytes
2023-10-06 00:56:51,748 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_seed_random (recursive=False)
2023-10-06 00:56:51,749 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_seed_random (recursive=False)
2023-10-06 00:56:51,750 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_seed_random'>)
2023-10-06 00:56:51,750 - cc_seed_random.py[DEBUG]: no command provided
2023-10-06 00:56:51,750 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2023-10-06 00:56:51,750 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2023-10-06 00:56:51,750 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2023-10-06 00:56:51,751 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7fe15f32adc0>)
2023-10-06 00:56:51,751 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2023-10-06 00:56:51,751 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2023-10-06 00:56:51,751 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2023-10-06 00:56:51,751 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2023-10-06 00:56:51,751 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_write_files - wb: [644] 25 bytes
2023-10-06 00:56:51,752 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_write_files (recursive=False)
2023-10-06 00:56:51,753 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_write_files (recursive=False)
2023-10-06 00:56:51,754 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_write_files'>)
2023-10-06 00:56:51,754 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2023-10-06 00:56:51,754 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2023-10-06 00:56:51,754 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2023-10-06 00:56:51,755 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2023-10-06 00:56:51,765 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_write_metadata - wb: [644] 24 bytes
2023-10-06 00:56:51,766 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_write_metadata (recursive=False)
2023-10-06 00:56:51,767 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_write_metadata (recursive=False)
2023-10-06 00:56:51,768 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_write_metadata'>)
2023-10-06 00:56:51,768 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2023-10-06 00:56:51,772 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2023-10-06 00:56:51,773 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2023-10-06 00:56:51,785 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2023-10-06 00:56:51,785 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2023-10-06 00:56:51,786 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2023-10-06 00:56:51,787 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2023-10-06 00:56:51,787 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2023-10-06 00:56:51,787 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2023-10-06 00:56:51,787 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2023-10-06 00:56:51,788 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2023-10-06 00:56:51,788 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fe15f32afd0>)
2023-10-06 00:56:51,788 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2023-10-06 00:56:51,788 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:51,818 - util.py[DEBUG]: Reading from /proc/1375/mountinfo (quiet=False)
2023-10-06 00:56:51,819 - util.py[DEBUG]: Read 2768 bytes from /proc/1375/mountinfo
2023-10-06 00:56:51,820 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2023-10-06 00:56:51,820 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2023-10-06 00:56:51,820 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2023-10-06 00:56:51,820 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2023-10-06 00:56:51,822 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:51,987 - util.py[DEBUG]: resize_devices took 0.168 seconds
2023-10-06 00:56:51,987 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2023-10-06 00:56:51,987 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2023-10-06 00:56:51,988 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2023-10-06 00:56:51,988 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2023-10-06 00:56:51,988 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fe15f32adc0>)
2023-10-06 00:56:51,988 - util.py[DEBUG]: Reading from /proc/1375/mountinfo (quiet=False)
2023-10-06 00:56:51,989 - util.py[DEBUG]: Read 2768 bytes from /proc/1375/mountinfo
2023-10-06 00:56:51,989 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2023-10-06 00:56:51,989 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2023-10-06 00:56:51,990 - util.py[DEBUG]: Forked child 1486 who will run callback log_time
2023-10-06 00:56:51,991 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2023-10-06 00:56:51,991 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:51,992 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2023-10-06 00:56:51,992 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2023-10-06 00:56:51,992 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2023-10-06 00:56:51,993 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_disk_setup - wb: [644] 25 bytes
2023-10-06 00:56:51,994 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_disk_setup (recursive=False)
2023-10-06 00:56:52,007 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_disk_setup (recursive=False)
2023-10-06 00:56:52,007 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_disk_setup'>)
2023-10-06 00:56:52,008 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2023-10-06 00:56:52,008 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2023-10-06 00:56:52,008 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2023-10-06 00:56:52,008 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_mounts - wb: [644] 25 bytes
2023-10-06 00:56:52,009 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_mounts (recursive=False)
2023-10-06 00:56:52,010 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_mounts (recursive=False)
2023-10-06 00:56:52,011 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_mounts'>)
2023-10-06 00:56:52,011 - cc_mounts.py[DEBUG]: mounts configuration is []
2023-10-06 00:56:52,011 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2023-10-06 00:56:52,012 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2023-10-06 00:56:52,012 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2023-10-06 00:56:52,012 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2023-10-06 00:56:52,012 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2023-10-06 00:56:52,012 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2023-10-06 00:56:52,012 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2023-10-06 00:56:52,012 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2023-10-06 00:56:52,012 - cc_mounts.py[DEBUG]: changed default device swap => None
2023-10-06 00:56:52,012 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2023-10-06 00:56:52,012 - cc_mounts.py[DEBUG]: no need to setup swap
2023-10-06 00:56:52,012 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2023-10-06 00:56:52,012 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2023-10-06 00:56:52,012 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2023-10-06 00:56:52,013 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2023-10-06 00:56:52,013 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fe15f5c9820>)
2023-10-06 00:56:52,013 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2023-10-06 00:56:52,013 - util.py[DEBUG]: Read 92 bytes from /var/lib/cloud/data/set-hostname
2023-10-06 00:56:52,013 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2023-10-06 00:56:52,013 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2023-10-06 00:56:52,013 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2023-10-06 00:56:52,014 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2023-10-06 00:56:52,014 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fe15f32adc0>)
2023-10-06 00:56:52,014 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-37-217.us-west-2.compute.internal (ip-172-31-37-217)
2023-10-06 00:56:52,014 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:52,030 - util.py[DEBUG]: backgrounded Resizing took 0.039 seconds
2023-10-06 00:56:52,033 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-37-217.us-west-2.compute.internal in 1 files
2023-10-06 00:56:52,033 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 43 bytes
2023-10-06 00:56:52,034 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2023-10-06 00:56:52,046 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2023-10-06 00:56:52,047 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2023-10-06 00:56:52,047 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2023-10-06 00:56:52,047 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2023-10-06 00:56:52,047 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fe15f32ac40>)
2023-10-06 00:56:52,048 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2023-10-06 00:56:52,048 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2023-10-06 00:56:52,048 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2023-10-06 00:56:52,048 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2023-10-06 00:56:52,048 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ca_certs - wb: [644] 25 bytes
2023-10-06 00:56:52,049 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ca_certs (recursive=False)
2023-10-06 00:56:52,050 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ca_certs (recursive=False)
2023-10-06 00:56:52,051 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ca_certs'>)
2023-10-06 00:56:52,051 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2023-10-06 00:56:52,051 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2023-10-06 00:56:52,051 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2023-10-06 00:56:52,051 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2023-10-06 00:56:52,052 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_rsyslog - wb: [644] 25 bytes
2023-10-06 00:56:52,052 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_rsyslog (recursive=False)
2023-10-06 00:56:52,054 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_rsyslog (recursive=False)
2023-10-06 00:56:52,054 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_rsyslog'>)
2023-10-06 00:56:52,054 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2023-10-06 00:56:52,054 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2023-10-06 00:56:52,054 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2023-10-06 00:56:52,055 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2023-10-06 00:56:52,055 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_selinux - wb: [644] 25 bytes
2023-10-06 00:56:52,056 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_selinux (recursive=False)
2023-10-06 00:56:52,057 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_selinux (recursive=False)
2023-10-06 00:56:52,057 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_selinux'>)
2023-10-06 00:56:52,079 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2023-10-06 00:56:52,079 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2023-10-06 00:56:52,079 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2023-10-06 00:56:52,079 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2023-10-06 00:56:52,079 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2023-10-06 00:56:52,079 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2023-10-06 00:56:52,079 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2023-10-06 00:56:52,080 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2023-10-06 00:56:52,080 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_users_groups - wb: [644] 25 bytes
2023-10-06 00:56:52,081 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_users_groups (recursive=False)
2023-10-06 00:56:52,084 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_users_groups (recursive=False)
2023-10-06 00:56:52,084 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_users_groups'>)
2023-10-06 00:56:52,098 - __init__.py[INFO]: User ec2-user already exists, skipping.
2023-10-06 00:56:52,098 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:52,184 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2023-10-06 00:56:52,198 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2023-10-06 00:56:52,200 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2023-10-06 00:56:52,201 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2023-10-06 00:56:52,202 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2023-10-06 00:56:52,203 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2023-10-06 00:56:52,203 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2023-10-06 00:56:52,203 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2023-10-06 00:56:52,203 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ssh - wb: [644] 24 bytes
2023-10-06 00:56:52,204 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ssh (recursive=False)
2023-10-06 00:56:52,206 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ssh (recursive=False)
2023-10-06 00:56:52,207 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ssh'>)
2023-10-06 00:56:52,208 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:52,259 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2023-10-06 00:56:52,285 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:52,307 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2023-10-06 00:56:52,326 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2023-10-06 00:56:52,326 - util.py[DEBUG]: Read 130 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2023-10-06 00:56:52,326 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2023-10-06 00:56:52,327 - util.py[DEBUG]: Read 210 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2023-10-06 00:56:52,328 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-10-06 00:56:52,329 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2023-10-06 00:56:52,330 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2023-10-06 00:56:52,331 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2023-10-06 00:56:52,332 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2023-10-06 00:56:52,332 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2023-10-06 00:56:52,333 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2023-10-06 00:56:52,333 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2023-10-06 00:56:52,333 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2023-10-06 00:56:52,333 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2023-10-06 00:56:52,333 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2023-10-06 00:56:52,333 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2023-10-06 00:56:52,334 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2023-10-06 00:56:52,334 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2023-10-06 00:56:52,345 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-10-06 00:56:52,345 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2023-10-06 00:56:52,346 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2023-10-06 00:56:52,348 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2023-10-06 00:56:52,349 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2023-10-06 00:56:52,349 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2023-10-06 00:56:52,350 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2023-10-06 00:56:52,350 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2023-10-06 00:56:52,350 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2023-10-06 00:56:52,350 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2023-10-06 00:56:52,350 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2023-10-06 00:56:52,350 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2023-10-06 00:56:52,351 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2023-10-06 00:56:52,353 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2023-10-06 00:56:52,353 - main.py[DEBUG]: Ran 17 modules with 0 failures
2023-10-06 00:56:52,354 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpuheudl91) - w: [644] 486 bytes/chars
2023-10-06 00:56:52,355 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-10-06 00:56:52,355 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2023-10-06 00:56:52,355 - util.py[DEBUG]: cloud-init mode 'init' took 2.464 seconds (2.47)
2023-10-06 00:56:52,355 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2023-10-06 00:56:53,405 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Fri, 06 Oct 2023 00:56:53 +0000. Up 11.94 seconds.
2023-10-06 00:56:53,407 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:53,415 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:53,425 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:53,425 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:53,429 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:53,429 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:53,435 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:53,435 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:53,445 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:53,445 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:53,450 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:53,450 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:53,465 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:53,465 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:53,468 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-10-06 00:56:53,469 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2023-10-06 00:56:53,472 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2023-10-06 00:56:53,472 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_set_passwords - wb: [644] 25 bytes
2023-10-06 00:56:53,476 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_set_passwords (recursive=False)
2023-10-06 00:56:53,479 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_set_passwords (recursive=False)
2023-10-06 00:56:53,480 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_set_passwords'>)
2023-10-06 00:56:53,480 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2023-10-06 00:56:53,507 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-10-06 00:56:53,508 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2023-10-06 00:56:53,508 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2023-10-06 00:56:53,508 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2023-10-06 00:56:53,509 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2023-10-06 00:56:53,509 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2023-10-06 00:56:53,509 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2023-10-06 00:56:53,509 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_yum_variables - wb: [644] 25 bytes
2023-10-06 00:56:53,510 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_yum_variables (recursive=False)
2023-10-06 00:56:53,512 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_yum_variables (recursive=False)
2023-10-06 00:56:53,513 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_yum_variables'>)
2023-10-06 00:56:53,513 - cc_yum_variables.py[INFO]: handling yum-variables
2023-10-06 00:56:53,513 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.1, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2023-10-06 00:56:53,513 - cc_yum_variables.py[INFO]: No yum vars to delete
2023-10-06 00:56:53,513 - cc_yum_variables.py[INFO]: No yum vars to set
2023-10-06 00:56:53,513 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2023-10-06 00:56:53,513 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2023-10-06 00:56:53,513 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2023-10-06 00:56:53,525 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_yum_add_repo - wb: [644] 24 bytes
2023-10-06 00:56:53,526 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_yum_add_repo (recursive=False)
2023-10-06 00:56:53,527 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_yum_add_repo (recursive=False)
2023-10-06 00:56:53,528 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_yum_add_repo'>)
2023-10-06 00:56:53,528 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2023-10-06 00:56:53,528 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2023-10-06 00:56:53,528 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2023-10-06 00:56:53,532 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2023-10-06 00:56:53,532 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ntp - wb: [644] 25 bytes
2023-10-06 00:56:53,533 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ntp (recursive=False)
2023-10-06 00:56:53,534 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ntp (recursive=False)
2023-10-06 00:56:53,535 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_ntp'>)
2023-10-06 00:56:53,535 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2023-10-06 00:56:53,535 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2023-10-06 00:56:53,535 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2023-10-06 00:56:53,535 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2023-10-06 00:56:53,535 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_timezone - wb: [644] 25 bytes
2023-10-06 00:56:53,536 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_timezone (recursive=False)
2023-10-06 00:56:53,537 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_timezone (recursive=False)
2023-10-06 00:56:53,537 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_timezone'>)
2023-10-06 00:56:53,537 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2023-10-06 00:56:53,537 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2023-10-06 00:56:53,537 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2023-10-06 00:56:53,537 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2023-10-06 00:56:53,537 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fd61b3c0f10>)
2023-10-06 00:56:53,537 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2023-10-06 00:56:53,538 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2023-10-06 00:56:53,538 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2023-10-06 00:56:53,538 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2023-10-06 00:56:53,538 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_runcmd - wb: [644] 24 bytes
2023-10-06 00:56:53,538 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_runcmd (recursive=False)
2023-10-06 00:56:53,539 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_runcmd (recursive=False)
2023-10-06 00:56:53,539 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-02f5f4c1d71eb856a/sem/config_runcmd'>)
2023-10-06 00:56:53,539 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2023-10-06 00:56:53,539 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2023-10-06 00:56:53,539 - main.py[DEBUG]: Ran 7 modules with 0 failures
2023-10-06 00:56:53,540 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpw5l3he3q) - w: [644] 514 bytes/chars
2023-10-06 00:56:53,540 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-10-06 00:56:53,540 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2023-10-06 00:56:53,540 - util.py[DEBUG]: cloud-init mode 'modules' took 0.322 seconds (0.32)
2023-10-06 00:56:53,540 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2023-10-06 00:56:54,432 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Fri, 06 Oct 2023 00:56:54 +0000. Up 12.97 seconds.
2023-10-06 00:56:54,434 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-10-06 00:56:54,434 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-10-06 00:56:54,437 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-10-06 00:56:54,438 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2023-10-06 00:56:54,438 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2023-10-06 00:56:54,438 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f825bc457c0>)
2023-10-06 00:56:54,438 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2023-10-06 00:57:05,785 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2023-10-06 00:57:05,785 - main.py[DEBUG]: Ran 1 modules with 0 failures
2023-10-06 00:57:05,786 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp4n0f_47d) - w: [644] 541 bytes/chars
2023-10-06 00:57:05,787 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpe39vmrty) - w: [644] 64 bytes/chars
2023-10-06 00:57:05,787 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2023-10-06 00:57:05,787 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-10-06 00:57:05,787 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2023-10-06 00:57:05,787 - util.py[DEBUG]: cloud-init mode 'modules' took 11.540 seconds (10.93)
2023-10-06 00:57:05,787 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
